export const LOG_IN = 'LOG_IN'
export const SET_LOGIN_IN_PROGRESS = 'SET_LOGIN_IN_PROGRESS'
export const SET_LOGIN_FINISHED = 'SET_LOGIN_FINISHED'
export const LOG_OUT = 'LOG_OUT'
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER'
export const SET_USER = 'SET_USER'
export const REMOVE_USER = 'REMOVE_USER'
